name: Cypress tests
on: [push, pull_request]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          # just perform install
          runTests: false
      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        env:
          WITH_COVERAGE: true
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 373658d4-4931-4ffd-9263-8eb78a838ab9
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          record: true
          parallel: true
          start: yarn vite --port 4200
          wait-on: http://localhost:4200
          # we have already installed all dependencies above
          install: false
          working-directory: packages/ui
