name: Cypress tests
on:
  push:
    paths:
      - "packages/ove/**"
  pull_request:
    paths:
      - "packages/ove/**"
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # the actual items in the array do not matter,
        # just the number - to force CI to sping 3 copies
        # of the current job in parallel
        machines: [1, 2, 3]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          # just perform install
          runTests: false
      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        env:
          WITH_COVERAGE: true
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 1ced39be-1a3a-4fd8-b2d5-a88951d9b766
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          record: true
          parallel: true
          start: yarn vite --port 4200
          wait-on: http://localhost:4200
          # we have already installed all dependencies above
          install: false
          working-directory: packages/ove
